### ISSUE TITLE
How to find whether mask applied or not to imageview?

### ISSUE THREAD

**Issue by myinnos** [davidHarush/Overlappingimageview#3]
Everything is fine, its works really well and i loved toggle method!

But i want know whether mask added to image view or not? 

Add imageview mask is there or not method. 

ex:   
```
if(img.isMaskVisibile()){
    return "masked";
}else{
    return "not masked";
}
```

**Comment by davidHarush** [comment]
Not really understand what you mean, Already there was a function that does it, but maybe you meant something else.

Anyway I did a little order and now there are two new functions.
`isMaskVisible(), isMaskSet()` 

And added the `Overlappingimageview.java` to the root folder.

Let me know if this solved your problem...

**Comment by myinnos** [comment]
Thanks for solution! but what is the difference between `isMaskVisible(), isMaskSet()` ?

**Comment by davidHarush** [comment]
`isMaskVisible()` it is like `View.getVisibility()`: return mask status.
`isMaskSet()`: return  True if mask is set, false otherwise. It actually to check if you provided the drawable id that needed to the mask.

**Comment by davidHarush** [comment]
Thanks :-)
